stages:
  - mirror

variables:
  GIT_STRATEGY: fetch  # 避免全量 clone，提高速度
  GIT_SSL_NO_VERIFY: "true"

mirror_to_github:
  stage: mirror
  image: $CI_DOCKER_BASE_REGISTRY:latest
  tags:
    - docker
  before_script:    
    - git config --global user.email "$GIT_CI_USER_NAME"
    - git config --global user.name "$GIT_CI_USER_EMAIL"

  script:
    - echo "Start mirror push to GitHub"
    - git config --global credential.helper ""
    # 添加 GitHub 远程仓库，带 token 认证
    - git remote add github https://$GITHUB_TOKEN@github.com/rabbitsaviola/test2.git
    # 推送 main 分支到 GitHub
    - git push --force --mirror github

